import type { PurchaseForm } from '@/api/oa/business/purchase/types'

export const allFields: PartialBooleanRecord<PurchaseForm> = {
  id: true,
  no: true,
  processName: false,
  subjectType: true,
  psId: true,
  deptId: true,
  type: true,
  purchaseMethod: true,
  businessCategory: true,
  objectCategory: true,
  serviceCategory: true,
  leaseType: true,
  isDeposit: true,
  contractId: true,
  contractNo: true,
  contractExecute: true,
  isOwnerSettlement: true,
  amount: true,
  notTaxAmount: true,
  realAmount: true,
  notTaxRealAmount: true,
  description: true,
  remark: true,
  itemList: true,
  ossIdList: true,
  hasPurchaseContract: true,
  purchaseContractIds: false,
  purchaseFiles: true,
  checkFiles: true,
  purchaseChange: true,
}
